export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const MEMORY_USER_LOGIN_FLAG = "MEMORY_USER_LOGIN_FLAG";

export const LOGOUT = 'LOGOUT';

