//get detail mainjob(include subjobs)

export const CREATE_JOB_BY_USER = "CREATE_JOB_BY_USER";
export const GET_ALL_JOBS_BY_USER = "GET_ALL_JOBS_BY_USER";
export const GET_LIST_JOB_BOOKED_BY_USER = "GET_LIST_JOB_BOOKED_BY_USER";
export const GET_DETAIL_JOB_CREATED_BY_USER = "GET_DETAIL_JOB_CREATED_BY_USER";
export const GET_DETAIL_SUBTYPE_JOBS = "GET_DETAIL_SUBTYPE_JOBS";
