
// get type of main job list
export const GET_MAIN_JOB_REQUEST = 'GET_MAIN_JOB_REQUEST';
export const GET_MAIN_JOB_SUCCESS = 'GET_MAIN_JOB_SUCCESS';
export const GET_MAIN_JOB_FAIL = 'GET_MAIN_JOB_FAIL';

// add new type of main job
export const ADD_NEW_MAIN_JOB_REQUEST = 'ADD_NEW_MAIN_JOB_REQUEST';
export const ADD_NEW_MAIN_JOB_SUCCESS = 'ADD_NEW_MAIN_JOB_SUCCESS';
export const ADD_NEW_MAIN_JOB_FAIL = 'ADD_NEW_MAIN_JOB_FAIL';

// update type of main job
export const UPDATE_MAIN_JOB_REQUEST = 'UPDATE_MAIN_JOB_REQUEST';
export const UPDATE_MAIN_JOB_SUCCESS = 'UPDATE_MAIN_JOB_SUCCESS';
export const UPDATE_MAIN_JOB_FAIL = 'UPDATE_MAIN_JOB_FAIL';

// delete type of main job
export const DELETE_MAIN_JOB_REQUEST = 'DELETE_MAIN_JOB_REQUEST';
export const DELETE_MAIN_JOB_SUCCESS = 'DELETE_MAIN_JOB_SUCCESS';
export const DELETE_MAIN_JOB_FAIL = 'DELETE_MAIN_JOB_FAIL';

// add new sub job type
export const ADD_NEW_SUB_JOB_REQUEST = 'ADD_NEW_SUB_JOB_REQUEST';
export const ADD_NEW_SUB_JOB_SUCCESS = 'ADD_NEW_SUB_JOB_SUCCESS';
export const ADD_NEW_SUB_JOB_FAIL = 'ADD_NEW_SUB_JOB_FAIL';

// update sub job type
export const UPDATE_SUB_JOB_REQUEST = 'UPDATE_SUB_JOB_REQUEST';
export const UPDATE_SUB_JOB_SUCCESS = 'UPDATE_SUB_JOB_SUCCESS';
export const UPDATE_SUB_JOB_FAIL = 'UPDATE_SUB_JOB_FAIL';

// delete sub job type
export const DELETE_SUB_JOB_REQUEST = 'DELETE_SUB_JOB_REQUEST';
export const DELETE_SUB_JOB_SUCCESS = 'DELETE_SUB_JOB_SUCCESS';
export const DELETE_SUB_JOB_FAIL = 'DELETE_SUB_JOB_FAIL';
